/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.d5.CMessageHttpProductUnit', null, global);
goog.exportSymbol('proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit', null, global);
goog.exportSymbol('proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit', null, global);
goog.exportSymbol('proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.d5.CMessageHttpProductUnit = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.d5.CMessageHttpProductUnit.repeatedFields_, null);
};
goog.inherits(proto.d5.CMessageHttpProductUnit, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.d5.CMessageHttpProductUnit.displayName = 'proto.d5.CMessageHttpProductUnit';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.d5.CMessageHttpProductUnit.repeatedFields_ = [13];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.d5.CMessageHttpProductUnit.prototype.toObject = function(opt_includeInstance) {
  return proto.d5.CMessageHttpProductUnit.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.d5.CMessageHttpProductUnit} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.d5.CMessageHttpProductUnit.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    title: jspb.Message.getFieldWithDefault(msg, 2, ""),
    description: jspb.Message.getFieldWithDefault(msg, 3, ""),
    price: +jspb.Message.getFieldWithDefault(msg, 4, 0.0),
    createtime: jspb.Message.getFieldWithDefault(msg, 5, 0),
    updatetime: jspb.Message.getFieldWithDefault(msg, 6, 0),
    brandid: jspb.Message.getFieldWithDefault(msg, 7, 0),
    producttype: jspb.Message.getFieldWithDefault(msg, 8, 0),
    categoryid: jspb.Message.getFieldWithDefault(msg, 9, 0),
    buyurl: jspb.Message.getFieldWithDefault(msg, 10, ""),
    brand: jspb.Message.getFieldWithDefault(msg, 11, ""),
    furniture: (f = msg.getFurniture()) && proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.toObject(includeInstance, f),
    productimagelistList: jspb.Message.toObjectList(msg.getProductimagelistList(),
    proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.toObject, includeInstance),
    dependentfilelist: jspb.Message.getFieldWithDefault(msg, 14, ""),
    buildingmaterial: (f = msg.getBuildingmaterial()) && proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.toObject(includeInstance, f),
    productcode: jspb.Message.getFieldWithDefault(msg, 16, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.d5.CMessageHttpProductUnit}
 */
proto.d5.CMessageHttpProductUnit.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.d5.CMessageHttpProductUnit;
  return proto.d5.CMessageHttpProductUnit.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.d5.CMessageHttpProductUnit} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.d5.CMessageHttpProductUnit}
 */
proto.d5.CMessageHttpProductUnit.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setTitle(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setPrice(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setCreatetime(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readInt64());
      msg.setUpdatetime(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setBrandid(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setProducttype(value);
      break;
    case 9:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setCategoryid(value);
      break;
    case 10:
      var value = /** @type {string} */ (reader.readString());
      msg.setBuyurl(value);
      break;
    case 11:
      var value = /** @type {string} */ (reader.readString());
      msg.setBrand(value);
      break;
    case 12:
      var value = new proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit;
      reader.readMessage(value,proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.deserializeBinaryFromReader);
      msg.setFurniture(value);
      break;
    case 13:
      var value = new proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit;
      reader.readMessage(value,proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.deserializeBinaryFromReader);
      msg.addProductimagelist(value);
      break;
    case 14:
      var value = /** @type {string} */ (reader.readString());
      msg.setDependentfilelist(value);
      break;
    case 15:
      var value = new proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit;
      reader.readMessage(value,proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.deserializeBinaryFromReader);
      msg.setBuildingmaterial(value);
      break;
    case 16:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductcode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.d5.CMessageHttpProductUnit.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.d5.CMessageHttpProductUnit.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.d5.CMessageHttpProductUnit} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.d5.CMessageHttpProductUnit.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getTitle();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getPrice();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getCreatetime();
  if (f !== 0) {
    writer.writeInt64(
      5,
      f
    );
  }
  f = message.getUpdatetime();
  if (f !== 0) {
    writer.writeInt64(
      6,
      f
    );
  }
  f = message.getBrandid();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getProducttype();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getCategoryid();
  if (f !== 0) {
    writer.writeInt32(
      9,
      f
    );
  }
  f = message.getBuyurl();
  if (f.length > 0) {
    writer.writeString(
      10,
      f
    );
  }
  f = message.getBrand();
  if (f.length > 0) {
    writer.writeString(
      11,
      f
    );
  }
  f = message.getFurniture();
  if (f != null) {
    writer.writeMessage(
      12,
      f,
      proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.serializeBinaryToWriter
    );
  }
  f = message.getProductimagelistList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      13,
      f,
      proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.serializeBinaryToWriter
    );
  }
  f = message.getDependentfilelist();
  if (f.length > 0) {
    writer.writeString(
      14,
      f
    );
  }
  f = message.getBuildingmaterial();
  if (f != null) {
    writer.writeMessage(
      15,
      f,
      proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.serializeBinaryToWriter
    );
  }
  f = message.getProductcode();
  if (f.length > 0) {
    writer.writeString(
      16,
      f
    );
  }
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.repeatedFields_, null);
};
goog.inherits(proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.displayName = 'proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit';
}
/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.repeatedFields_ = [9];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.toObject = function(opt_includeInstance) {
  return proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.toObject = function(includeInstance, msg) {
  var f, obj = {
    productid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    uepath: jspb.Message.getFieldWithDefault(msg, 2, ""),
    pakurl: jspb.Message.getFieldWithDefault(msg, 3, ""),
    length: +jspb.Message.getFieldWithDefault(msg, 4, 0.0),
    depth: +jspb.Message.getFieldWithDefault(msg, 5, 0.0),
    height: +jspb.Message.getFieldWithDefault(msg, 6, 0.0),
    isinteractive: jspb.Message.getFieldWithDefault(msg, 7, 0),
    intelligenttype: jspb.Message.getFieldWithDefault(msg, 8, 0),
    furniturecoloridlistList: jspb.Message.getRepeatedField(msg, 9),
    furniturestyleid: jspb.Message.getFieldWithDefault(msg, 10, 0),
    furnituremainmaterialid: jspb.Message.getFieldWithDefault(msg, 11, 0),
    detailinfo: jspb.Message.getFieldWithDefault(msg, 12, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit;
  return proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setUepath(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPakurl(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setLength(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setDepth(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setHeight(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIsinteractive(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIntelligenttype(value);
      break;
    case 9:
      var value = /** @type {!Array<number>} */ (reader.readPackedInt32());
      msg.setFurniturecoloridlistList(value);
      break;
    case 10:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFurniturestyleid(value);
      break;
    case 11:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setFurnituremainmaterialid(value);
      break;
    case 12:
      var value = /** @type {string} */ (reader.readString());
      msg.setDetailinfo(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProductid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getUepath();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getPakurl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getLength();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
  f = message.getDepth();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
  f = message.getHeight();
  if (f !== 0.0) {
    writer.writeFloat(
      6,
      f
    );
  }
  f = message.getIsinteractive();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getIntelligenttype();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
  f = message.getFurniturecoloridlistList();
  if (f.length > 0) {
    writer.writePackedInt32(
      9,
      f
    );
  }
  f = message.getFurniturestyleid();
  if (f !== 0) {
    writer.writeInt32(
      10,
      f
    );
  }
  f = message.getFurnituremainmaterialid();
  if (f !== 0) {
    writer.writeInt32(
      11,
      f
    );
  }
  f = message.getDetailinfo();
  if (f.length > 0) {
    writer.writeString(
      12,
      f
    );
  }
};


/**
 * optional string productId = 1;
 * @return {string}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.getProductid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.setProductid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string uePath = 2;
 * @return {string}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.getUepath = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.setUepath = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string pakUrl = 3;
 * @return {string}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.getPakurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.setPakurl = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional float length = 4;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.getLength = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.setLength = function(value) {
  jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional float depth = 5;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.getDepth = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 5, 0.0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.setDepth = function(value) {
  jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional float height = 6;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.getHeight = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 6, 0.0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.setHeight = function(value) {
  jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional int32 isInteractive = 7;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.getIsinteractive = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.setIsinteractive = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 intelligentType = 8;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.getIntelligenttype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.setIntelligenttype = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * repeated int32 furnitureColorIdList = 9;
 * @return {!Array<number>}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.getFurniturecoloridlistList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedField(this, 9));
};


/** @param {!Array<number>} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.setFurniturecoloridlistList = function(value) {
  jspb.Message.setField(this, 9, value || []);
};


/**
 * @param {!number} value
 * @param {number=} opt_index
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.addFurniturecoloridlist = function(value, opt_index) {
  jspb.Message.addToRepeatedField(this, 9, value, opt_index);
};


proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.clearFurniturecoloridlistList = function() {
  this.setFurniturecoloridlistList([]);
};


/**
 * optional int32 furnitureStyleId = 10;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.getFurniturestyleid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 10, 0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.setFurniturestyleid = function(value) {
  jspb.Message.setProto3IntField(this, 10, value);
};


/**
 * optional int32 furnitureMainMaterialId = 11;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.getFurnituremainmaterialid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 11, 0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.setFurnituremainmaterialid = function(value) {
  jspb.Message.setProto3IntField(this, 11, value);
};


/**
 * optional string detailInfo = 12;
 * @return {string}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.getDetailinfo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 12, ""));
};


/** @param {string} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit.prototype.setDetailinfo = function(value) {
  jspb.Message.setProto3StringField(this, 12, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.displayName = 'proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.toObject = function(opt_includeInstance) {
  return proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.toObject = function(includeInstance, msg) {
  var f, obj = {
    productid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    isforfloor: jspb.Message.getFieldWithDefault(msg, 2, 0),
    isforwall: jspb.Message.getFieldWithDefault(msg, 3, 0),
    isforceiling: jspb.Message.getFieldWithDefault(msg, 4, 0),
    materialid: jspb.Message.getFieldWithDefault(msg, 5, ""),
    detailinfo: jspb.Message.getFieldWithDefault(msg, 6, ""),
    length: jspb.Message.getFieldWithDefault(msg, 7, 0),
    width: jspb.Message.getFieldWithDefault(msg, 8, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit;
  return proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductid(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIsforfloor(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIsforwall(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setIsforceiling(value);
      break;
    case 5:
      var value = /** @type {string} */ (reader.readString());
      msg.setMaterialid(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setDetailinfo(value);
      break;
    case 7:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setLength(value);
      break;
    case 8:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWidth(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProductid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getIsforfloor();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getIsforwall();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getIsforceiling();
  if (f !== 0) {
    writer.writeInt32(
      4,
      f
    );
  }
  f = message.getMaterialid();
  if (f.length > 0) {
    writer.writeString(
      5,
      f
    );
  }
  f = message.getDetailinfo();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getLength();
  if (f !== 0) {
    writer.writeInt32(
      7,
      f
    );
  }
  f = message.getWidth();
  if (f !== 0) {
    writer.writeInt32(
      8,
      f
    );
  }
};


/**
 * optional string productId = 1;
 * @return {string}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.getProductid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.setProductid = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 isForFloor = 2;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.getIsforfloor = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.setIsforfloor = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 isForWall = 3;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.getIsforwall = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.setIsforwall = function(value) {
  jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * optional int32 isForCeiling = 4;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.getIsforceiling = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.setIsforceiling = function(value) {
  jspb.Message.setProto3IntField(this, 4, value);
};


/**
 * optional string materialId = 5;
 * @return {string}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.getMaterialid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 5, ""));
};


/** @param {string} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.setMaterialid = function(value) {
  jspb.Message.setProto3StringField(this, 5, value);
};


/**
 * optional string detailInfo = 6;
 * @return {string}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.getDetailinfo = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/** @param {string} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.setDetailinfo = function(value) {
  jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * optional int32 length = 7;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.getLength = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.setLength = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 width = 8;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.getWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit.prototype.setWidth = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.displayName = 'proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.prototype.toObject = function(opt_includeInstance) {
  return proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.toObject = function(includeInstance, msg) {
  var f, obj = {
    id: jspb.Message.getFieldWithDefault(msg, 1, ""),
    displayindex: jspb.Message.getFieldWithDefault(msg, 2, 0),
    fileurl: jspb.Message.getFieldWithDefault(msg, 3, ""),
    productid: jspb.Message.getFieldWithDefault(msg, 4, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit;
  return proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setDisplayindex(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setFileurl(value);
      break;
    case 4:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductid(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getDisplayindex();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getFileurl();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getProductid();
  if (f.length > 0) {
    writer.writeString(
      4,
      f
    );
  }
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional int32 displayIndex = 2;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.prototype.getDisplayindex = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.prototype.setDisplayindex = function(value) {
  jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional string fileUrl = 3;
 * @return {string}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.prototype.getFileurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.prototype.setFileurl = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional string productId = 4;
 * @return {string}
 */
proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.prototype.getProductid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 4, ""));
};


/** @param {string} value */
proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit.prototype.setProductid = function(value) {
  jspb.Message.setProto3StringField(this, 4, value);
};


/**
 * optional string id = 1;
 * @return {string}
 */
proto.d5.CMessageHttpProductUnit.prototype.getId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.d5.CMessageHttpProductUnit.prototype.setId = function(value) {
  jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string title = 2;
 * @return {string}
 */
proto.d5.CMessageHttpProductUnit.prototype.getTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/** @param {string} value */
proto.d5.CMessageHttpProductUnit.prototype.setTitle = function(value) {
  jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.d5.CMessageHttpProductUnit.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/** @param {string} value */
proto.d5.CMessageHttpProductUnit.prototype.setDescription = function(value) {
  jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional float price = 4;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.prototype.getPrice = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 4, 0.0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.prototype.setPrice = function(value) {
  jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional int64 createTime = 5;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.prototype.getCreatetime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 5, 0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.prototype.setCreatetime = function(value) {
  jspb.Message.setProto3IntField(this, 5, value);
};


/**
 * optional int64 updateTime = 6;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.prototype.getUpdatetime = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 6, 0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.prototype.setUpdatetime = function(value) {
  jspb.Message.setProto3IntField(this, 6, value);
};


/**
 * optional int32 brandId = 7;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.prototype.getBrandid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.prototype.setBrandid = function(value) {
  jspb.Message.setProto3IntField(this, 7, value);
};


/**
 * optional int32 productType = 8;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.prototype.getProducttype = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 8, 0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.prototype.setProducttype = function(value) {
  jspb.Message.setProto3IntField(this, 8, value);
};


/**
 * optional int32 categoryId = 9;
 * @return {number}
 */
proto.d5.CMessageHttpProductUnit.prototype.getCategoryid = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 9, 0));
};


/** @param {number} value */
proto.d5.CMessageHttpProductUnit.prototype.setCategoryid = function(value) {
  jspb.Message.setProto3IntField(this, 9, value);
};


/**
 * optional string buyUrl = 10;
 * @return {string}
 */
proto.d5.CMessageHttpProductUnit.prototype.getBuyurl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 10, ""));
};


/** @param {string} value */
proto.d5.CMessageHttpProductUnit.prototype.setBuyurl = function(value) {
  jspb.Message.setProto3StringField(this, 10, value);
};


/**
 * optional string brand = 11;
 * @return {string}
 */
proto.d5.CMessageHttpProductUnit.prototype.getBrand = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 11, ""));
};


/** @param {string} value */
proto.d5.CMessageHttpProductUnit.prototype.setBrand = function(value) {
  jspb.Message.setProto3StringField(this, 11, value);
};


/**
 * optional CMessageHttpFurnitureUnit furniture = 12;
 * @return {?proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit}
 */
proto.d5.CMessageHttpProductUnit.prototype.getFurniture = function() {
  return /** @type{?proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit} */ (
    jspb.Message.getWrapperField(this, proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit, 12));
};


/** @param {?proto.d5.CMessageHttpProductUnit.CMessageHttpFurnitureUnit|undefined} value */
proto.d5.CMessageHttpProductUnit.prototype.setFurniture = function(value) {
  jspb.Message.setWrapperField(this, 12, value);
};


proto.d5.CMessageHttpProductUnit.prototype.clearFurniture = function() {
  this.setFurniture(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.d5.CMessageHttpProductUnit.prototype.hasFurniture = function() {
  return jspb.Message.getField(this, 12) != null;
};


/**
 * repeated CMessageHttpProductImageUnit productImageList = 13;
 * @return {!Array<!proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit>}
 */
proto.d5.CMessageHttpProductUnit.prototype.getProductimagelistList = function() {
  return /** @type{!Array<!proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit, 13));
};


/** @param {!Array<!proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit>} value */
proto.d5.CMessageHttpProductUnit.prototype.setProductimagelistList = function(value) {
  jspb.Message.setRepeatedWrapperField(this, 13, value);
};


/**
 * @param {!proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit=} opt_value
 * @param {number=} opt_index
 * @return {!proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit}
 */
proto.d5.CMessageHttpProductUnit.prototype.addProductimagelist = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 13, opt_value, proto.d5.CMessageHttpProductUnit.CMessageHttpProductImageUnit, opt_index);
};


proto.d5.CMessageHttpProductUnit.prototype.clearProductimagelistList = function() {
  this.setProductimagelistList([]);
};


/**
 * optional string dependentFileList = 14;
 * @return {string}
 */
proto.d5.CMessageHttpProductUnit.prototype.getDependentfilelist = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 14, ""));
};


/** @param {string} value */
proto.d5.CMessageHttpProductUnit.prototype.setDependentfilelist = function(value) {
  jspb.Message.setProto3StringField(this, 14, value);
};


/**
 * optional CMessageHttpBuildingMaterialUnit buildingMaterial = 15;
 * @return {?proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit}
 */
proto.d5.CMessageHttpProductUnit.prototype.getBuildingmaterial = function() {
  return /** @type{?proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit} */ (
    jspb.Message.getWrapperField(this, proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit, 15));
};


/** @param {?proto.d5.CMessageHttpProductUnit.CMessageHttpBuildingMaterialUnit|undefined} value */
proto.d5.CMessageHttpProductUnit.prototype.setBuildingmaterial = function(value) {
  jspb.Message.setWrapperField(this, 15, value);
};


proto.d5.CMessageHttpProductUnit.prototype.clearBuildingmaterial = function() {
  this.setBuildingmaterial(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.d5.CMessageHttpProductUnit.prototype.hasBuildingmaterial = function() {
  return jspb.Message.getField(this, 15) != null;
};


/**
 * optional string productCode = 16;
 * @return {string}
 */
proto.d5.CMessageHttpProductUnit.prototype.getProductcode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 16, ""));
};


/** @param {string} value */
proto.d5.CMessageHttpProductUnit.prototype.setProductcode = function(value) {
  jspb.Message.setProto3StringField(this, 16, value);
};


goog.object.extend(exports, proto.d5);
